### ISSUE TITLE
Failure for writing large dataframe to memsql from spark

### ISSUE THREAD

**Issue by chutianwen** [memsql/memsql-spark-connector#15]
I am using this memsql-spark connector for writing dataframe from spark to memsql. This library works fine when the size of dataframe is not large. From number of lines aspect, if the dataframe has rows smaller than several millions, then it works. However, when the dataframe has more than 10 million rows, then the program may fail, if it has rows as large as billions, then it will definitely fails. 

I am using spark and memsql on a single large server, so memsql master node and spark driver node are same.

The main error in the log is : java.sql.SQLException: Unable to connect to leaf @10.1.10.40:3307 with user root, using password NO: [2005] Timed out trying to connect to '10.1.10.40':3307 after 30 seconds.

This issue bothers me long time, I have updated memsql and this connect library, yet still not solved the problem.

**Comment by allanca** [comment]
Hi Tianwen,

Sounds like you're working with some serious amounts of data. Do you see
any errors in the MemSQL logs when you get the timeout? It's possible that
you're hitting some form of resource exhaustion.

-Allan

**Comment by mnarrell** [comment]
Thats interesting.  I run into similar issues where the MemSQL engine cannot keep up (or has genreal issues) with the connector load.  I have issues with table locks constantly.

**Comment by chutianwen** [comment]
Hi Matt!

Actually, I solve this by coalesce the dataframe before saveToMemsql. I
have 96 cores, yet I have to use df.coalesce(48).saveToMemSQL.

I think this is because of the memory issue for memsql. If too many writers
writing too large file in buffer at the same time.

Best,
Tianwen

**Comment by choochootrain** [comment]
Hi Tianwen,

Are all your memsql nodes on one machine or just the master aggregator and the spark master? This could just be overwhelming the network but but MemSQL should be able to handle very large loads from dataframes if the network permits. Here's a couple things to try:

* By default, we use a `LOAD DATA` statement to insert into MemSQL but you can configure the connector to use inserts instead. In both `saveToMemSQL` and the pipeline load config, there are `onDuplicateKeySQL` and `upsertBatchSize` which enable inserts and also control the batch size. See
http://docs.memsql.com/docs/streamliner-pipelines?utm_source=ops&utm_medium=link&utm_campaign=ref#custom-loader and https://github.com/memsql/memsql-spark-connector/blob/6a8d8c7b3d9169d0825f71ed4fadb5c9dde135c6/connectorLib/src/main/scala/org/apache/spark/sql/memsql/SaveToMemSQLConf.scala#L22 for details.

* An alternative (undocumented) approach is to use keyless sharding on your tables. If your schema permits, you can use an empty shard key (`SHARD()`) in your target table, and enable the `useKeylessShardingOptimization` option in the connector, which will load directly into the leaves instead of through the aggregators. See
https://github.com/memsql/memsql-spark-connector/blob/6a8d8c7b3d9169d0825f71ed4fadb5c9dde135c6/connectorLib/src/main/scala/org/apache/spark/sql/memsql/SaveToMemSQLConf.scala#L24 for details.

Hurshal

**Comment by chutianwen** [comment]
Hi Hurshal!

The information you provided is very meaningful, it would be better if you
could provide an example how to use this.

like how to change the "load data" mode to "insert", which function I
should modify?

Best,
Tianwen

**Comment by chandransuraj** [comment]
I guess right now its just via this( from SparkImplicits.scala
<https://github.com/memsql/memsql-spark-connector/blob/6a8d8c7b3d9169d0825f71ed4fadb5c9dde135c6/connectorLib/src/main/scala/org/apache/spark/sql/memsql/SparkImplicits.scala>
):

val useInsert = df.schema.size == 0 ||
                      saveConf.onDuplicateKeySQL.isDefined ||
                      df.schema.exists(_.dataType == BinaryType)



Not sure if there's a better way of enabling Insert.
Thanks,
Suraj.

**Comment by chandransuraj** [comment]
actually please ignore below, I didn't read Hurshal's mail. :)

**Comment by choochootrain** [comment]
Tianwen, Suraj,

are you using MemSQL Streamliner or are you just using the MemSQL spark connector and calling `saveToMemSQL` yourself? The options are available for both in the first 2 links I sent.

Hurshal

**Comment by chutianwen** [comment]
I am just using MemSQL spark connector and calling saveToMemSQL. 

So currently I am using Dataframe.saveToMemSQL(databaseName: String, tableName: String).
 In order to change mode to "insert", should I call Dataframe.saveToMemSQL(tableIdentifier: TableIdentifier, saveConf: SaveToMemSQLConf) this way? 

So create a tableIdentifier based on  (databaseName, tableName), then create a SaveToMemSQLConf(case class) object. 
If so, what should I import in the header to make class SaveToMemSQLConf `invokable`. .

**Comment by choochootrain** [comment]
`SaveToMemSQLConf` is imported from `org.apache.spark.sql.memsql`. See the [scaladocs](http://memsql.github.io/memsql-spark-connector/latest/api/#org.apache.spark.sql.memsql.SaveToMemSQLConf) for more info
