### ISSUE TITLE
SparkContext has been shutdown

### ISSUE THREAD

**Issue by 0x0ece** [memsql/memsql-spark-connector#23]
In some weird cases, an exception in one pipeline may cause SparkContext to be shutdown.

(For example, I was able to get into that situation with a pipeline that repeatedly failed with `kafka.common.OffsetOutOfRangeException`... not really sure why SparkContext has been shutdown, but that happened.)

As a result, all other pipelines enter in a loop where each batch fails with:

```
java.lang.IllegalStateException: SparkContext has been shutdown
```

I think it could be useful to catch this exception, and possibly perform a nice restart? Not sure what else one can do if SparkContext has been shutdown...

**Comment by choochootrain** [comment]
Streamliner is `spark-submit`ed job, so it doesn't have the ability to restart itself without shelling out to the `spark-submit` script which I'd like to avoid if possible

A nicer solution would be to signal this condition in the REST API so that MemSQL Ops could restart the job itself. Is an endpoint for this sufficient for your setup?

**Comment by ecesena** [comment]
Sure, it would be nice. Also, maybe just stopping nicely the pipelines... it's useless to have them running for nothing.

**Comment by choochootrain** [comment]
i'll task it out but as always, pull requests are welcome :)
