### ISSUE TITLE
Does not work with Spark 2.0

### ISSUE THREAD

**Issue by abstract-karshit** [memsql/memsql-spark-connector#24]
Hi,
I was using the connector with Spark 1.6.2 and it was working fine, once we upgraded it to Spark 2.0, it creates the table but doesn't write anything.

**Comment by AlexStanovsky** [comment]
Hi @abstract-karshit,
I want to start using Memsql Spark connector with Spark 2.0, Can you update me if you succeeded to do so ?
Also have you complied the memsql-spark-connecter with Spark 2.0 jars ?

Thanks

**Comment by choochootrain** [comment]
the connector is compiled against spark 1.5.2 - our sql pushdown code hooks into the catalyst optimizer so running against spark 2.0 won't work out of the box.

porting to spark 2.0 will require some amount of rewriting since the catalyst internal apis have changed. we're looking into doing this but not timeline yet.

**Comment by ashitabh** [comment]
Its almost 3 months , but Memsql is still supporting Spark 1.5 only. I was almost ready to recommend memsql to a client when I got stuck with this issue in Spark 2.0. Memsql context is no more working with spark 2.0, the only option left is to use jdbc for query and data loading just like any other database.Is memsql going out of business ?Why is it taking so long to upgrade to Spark 2.0 ?

**Comment by rick-memsql** [comment]
The MemSQL Spark connector will support Spark 2.0 by February 2017 (as announced here: http://www.memsql.com/releases/apache-spark-integration/).
